name: sgs 
description: Monitoring Application for the Smart Grow System

version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  line_icons: ^0.2.0
  weather_icons: ^2.0.1
  page_transition: ^1.1.6
  #image: ^2.1.12
  flare_flutter: ^2.0.6
  firebase_core: ^0.4.0+9
  firebase_database: ^3.1.1
  firebase_storage: ^3.0.8
  firebase: ^5.0.4
  fl_chart: ^0.9.4
  google_fonts: ^1.1.0
  flutter_svg: ^0.18.1
  xml: ^4.2.0
  outline_material_icons: ^0.1.1
  provider: ^4.3.2
  service_locator: ^1.0.0
  flutter_skeleton: ^0.1.0+1
  cached_network_image: ^2.3.3
  
dev_dependencies:
  flutter_launcher_icons: "^0.7.5"
  flutter_test:
    sdk: flutter

flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/leaf.png"
  image_path_android: "assets/leaf.png"
  #adaptive_icon_background: "assets/launcher/background.png"
  #adaptive_icon_foreground: "assets/launcher/foreground.png"

flutter:
  assets:
    - assets/
    - assets/icons/
    - assets/images/
    - assets/flares/
    - assets/leaf.svg
  uses-material-design: true
  fonts:
    - family: OpenSans
      fonts:
        - asset: fonts/OpenSans-Regular.ttf
        - asset: fonts/OpenSans-Italic.ttf
          style: italic
    - family: SGS_CustomIcon
      fonts:
        - asset: fonts/SGS_CustomIcon.ttf
